Added info about SCENARIO in presentation_catch.md
coders-school/testing pull request #1
Opened 2020-07-19 16:18 UTC by niemarcin

In `Organizacja testów` chapter - added SCENARIO info and mapping between TEST_CASE and SCENARIO.

2020-07-20 11:17 UTC, ziobron requested changes

2020-07-20 11:17 UTC, ziobron commented on module1/presentation_catch.md
> +Gdzie `TEST_CASE` mapuje się na `SCENARIO`, natomiast `SECTION` na `GIVEN`, `WHEN` i `THEN`.
Jest odwrotnie. 
SCENARIO mapuje się na TEST_CASE, a GIVEN, WHEN i THEN na SECTION.

https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#bdd-style

2020-07-20 11:51 UTC, niemarcin commented on module1/presentation_catch.md
> +Gdzie `TEST_CASE` mapuje się na `SCENARIO`, natomiast `SECTION` na `GIVEN`, `WHEN` i `THEN`.
@ziobron 
updated

2020-07-20 19:49 UTC, ziobron requested changes

2020-07-20 19:49 UTC, ziobron commented on module1/presentation_catch.md
> +* <!-- .element: class="fragment fade-in" --> <code>TEST_CASE( test name , [ tags ] )</code>
To akurat powinno zostać tak jak było :)
To co w nawiasach jest opcjonalne, więc jeśli nie ma tagów to i przecinka nie będzie. W wielu dokumentacjach stosuje się tego typu zapis.
Dla SCENARIO będzie podobnie.

2020-07-20 19:49 UTC, ziobron commented on module1/presentation_catch.md
> +Lub
Aby być zgodnym ze standardami MD trzeba jeszcze wstawić pustą linię przed i po liście (czyli przed i po "Lub")

2020-07-20 19:49 UTC, ziobron commented on module1/presentation_catch.md
> +Gdzie `SCENARIO` mapuje się na `TEST_CASE`, natomiast `GIVEN`, `WHEN` i `THEN` na `SECTION`.
Pusta linia pomiędzy tekstem a listą.

2020-07-21 19:50 UTC, niemarcin commented
@ziobron thanks for your comments! :)

2020-07-22 07:56 UTC, ziobron approved these changes

2020-07-22 07:56 UTC, merged